export const FETCH_PRODUCTS = "PRODUCTS/FETCH_ALL";

export const ADD_PRODUCT = 'CART/ADD_PRODUCT';
export const DELETE_PRODUCT = 'CART/DELETE_PRODUCT';
export const REMOVE_PRODUCT = "CART/REMOVE_PRODUCT"
